# Generated by Django 2.2 on 2019-09-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_content_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
